# Lab | Numpy Deep Dive

### 1. Import the NUMPY package under the name np.


In [1]:
import numpy as np




### 2. Print the NUMPY version and the configuration.


In [3]:
np.version


<module 'numpy.version' from 'c:\\Users\\Ayse\\anaconda3\\Lib\\site-packages\\numpy\\version.py'>

### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?


In [13]:
aa = np.random.rand(2, 3, 5)


In [14]:
aa

array([[[0.98320427, 0.1666072 , 0.00368792, 0.99862965, 0.61909566],
        [0.96829814, 0.43849452, 0.13792663, 0.44594055, 0.17236418],
        [0.68169262, 0.51197873, 0.48016163, 0.74097272, 0.51929058]],

       [[0.74304996, 0.73290153, 0.81216442, 0.72825874, 0.4886838 ],
        [0.57782239, 0.13834802, 0.14740111, 0.48655075, 0.08527318],
        [0.9043776 , 0.02760362, 0.07547112, 0.39774126, 0.10556655]]])

In [15]:
tensor_a = np.random.randint(3, size=(2, 3, 5))
print("\nRandom tensor:")
print(tensor_a)



Random tensor:
[[[1 2 1 2 2]
  [1 0 2 0 2]
  [1 1 2 0 0]]

 [[2 1 2 1 0]
  [1 1 1 2 1]
  [1 0 2 0 0]]]



### 4. Print a.


In [9]:
tensor_a

array([[[1, 1, 2, 0, 0],
        [0, 1, 2, 1, 2],
        [0, 1, 0, 1, 1]],

       [[0, 2, 2, 0, 1],
        [0, 1, 0, 0, 0],
        [2, 1, 2, 2, 1]]], dtype=int32)

### 5. Create a 5x2x3 3-dimensional array with all values equaling 1.
### Assign the array to variable "b"


In [18]:
tensor_b = np.ones((5, 2, 3))



### 6. Print b.


In [19]:
tensor_b


array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])


### 7. Do a and b have the same size? How do you prove that in Python code?


In [ ]:
print(tensor_a.size)
print(tensor_b.size)



#They are the same.

30
30


In [ ]:
equal_result = (tensor_a.size == tensor_b.size)
print("Equality Comparison Result:")
print(equal_result)

Equality Comparison Result:
True



### 8. Are you able to add a and b? Why or why not?


In [ ]:
#You cannot add a andb, their shapes are not compatible,but we can make them compatible- we just have to transpose or reshape them.




### 9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".


In [28]:
#tensor_b is currently: 5x2x3. I want to transform it to a 2x3x5.
#axis 0:5; axis 1:2; axis: 2: 3 has to be arranged to axis 1, axis 2, axis 0.

tensor_c = np.transpose(tensor_b, (1, 2, 0))
print (tensor_c.shape)


(2, 3, 5)



### 10. Try to add a and c. Now it should work. Assign the sum to variable "d". But why does it work now?


In [ ]:
tensor_d = tensor_a + tensor_c
print(tensor_d)

#It works now because they have the same shape.


[[[2. 3. 2. 3. 3.]
  [2. 1. 3. 1. 3.]
  [2. 2. 3. 1. 1.]]

 [[3. 2. 3. 2. 1.]
  [2. 2. 2. 3. 2.]
  [2. 1. 3. 1. 1.]]]



### 11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.


In [ ]:
print ("tensor_a")
print(tensor_a)
(print ("tensor_d:"))
print(tensor_d)

#tensor_d is similar to tensor_a, just each value added 1.


tensor_a
[[[1 2 1 2 2]
  [1 0 2 0 2]
  [1 1 2 0 0]]

 [[2 1 2 1 0]
  [1 1 1 2 1]
  [1 0 2 0 0]]]
tensor_d:
[[[2. 3. 2. 3. 3.]
  [2. 1. 3. 1. 3.]
  [2. 2. 3. 1. 1.]]

 [[3. 2. 3. 2. 1.]
  [2. 2. 2. 3. 2.]
  [2. 1. 3. 1. 1.]]]



### 12. Multiply a and c. Assign the result to e.


In [38]:
tensor_e = tensor_a * tensor_c
tensor_e

array([[[1., 2., 1., 2., 2.],
        [1., 0., 2., 0., 2.],
        [1., 1., 2., 0., 0.]],

       [[2., 1., 2., 1., 0.],
        [1., 1., 1., 2., 1.],
        [1., 0., 2., 0., 0.]]])



### 13. Does e equal to a? Why or why not?


In [ ]:
#tensor_c  is full of ones, so multiplying it with tensor_a doesn not change any values, which is why tensor_a is equal to tensor_e.





### 14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"


In [43]:
d_max = np.max(tensor_d); print("Max value: ", d_max)
d_min = np.min(tensor_d);print("Min value: ", d_min)
d_mean = np.mean(tensor_d); print("Mean: ", d_mean)


Max value:  3.0
Min value:  1.0
Mean:  2.066666666666667



### 15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.


In [46]:
tensor_f = np.empty((2, 3, 5))
tensor_f

array([[[2., 3., 2., 3., 3.],
        [2., 1., 3., 1., 3.],
        [2., 2., 3., 1., 1.]],

       [[3., 2., 3., 2., 1.],
        [2., 2., 2., 3., 2.],
        [2., 1., 3., 1., 1.]]])




### 16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.



In [47]:
for i in range(2): #first dimension
    for j in range(3): #second dimension
        for k in range(5): #third dimension
            value = tensor_d[i][j][k]

            if value == d_min:
                tensor_f[i][j][k] = 0
            elif value == d_max:
                tensor_f[i][j][k] = 100
            elif value == d_mean:
                tensor_f[i][j][k] = 50
            elif value > d_min and value < d_mean:
                tensor_f[i][j][k] = 25
            elif value > d_mean and value < d_max:
                tensor_f[i][j][k] = 75

tensor_f



array([[[ 25., 100.,  25., 100., 100.],
        [ 25.,   0., 100.,   0., 100.],
        [ 25.,  25., 100.,   0.,   0.]],

       [[100.,  25., 100.,  25.,   0.],
        [ 25.,  25.,  25., 100.,  25.],
        [ 25.,   0., 100.,   0.,   0.]]])





### 17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])



In [52]:
print("d: ", tensor_d)
print("f: ", tensor_f)


d:  [[[2. 3. 2. 3. 3.]
  [2. 1. 3. 1. 3.]
  [2. 2. 3. 1. 1.]]

 [[3. 2. 3. 2. 1.]
  [2. 2. 2. 3. 2.]
  [2. 1. 3. 1. 1.]]]
f:  [[[ 25. 100.  25. 100. 100.]
  [ 25.   0. 100.   0. 100.]
  [ 25.  25. 100.   0.   0.]]

 [[100.  25. 100.  25.   0.]
  [ 25.  25.  25. 100.  25.]
  [ 25.   0. 100.   0.   0.]]]


### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.

In [54]:
tensor_g = np.empty_like(tensor_f, dtype=object)


for i in range(2):
    for j in range (3):
        for k in range (5):
            val = tensor_f[i][j][k]
            if val == 0:
                tensor_g[i][j][k] = "A"
            elif val == 25:
                tensor_g[i][j][k] = "B"
            elif val == 50:
                tensor_g[i][j][k] = "C"
            elif val == 75:
                tensor_g[i][j][k] = "D"
            elif val == 100:
                tensor_g[i][j][k] = "E"
            
tensor_g

array([[['B', 'E', 'B', 'E', 'E'],
        ['B', 'A', 'E', 'A', 'E'],
        ['B', 'B', 'E', 'A', 'A']],

       [['E', 'B', 'E', 'B', 'A'],
        ['B', 'B', 'B', 'E', 'B'],
        ['B', 'A', 'E', 'A', 'A']]], dtype=object)